### ISSUE TITLE
[QUESTION] Access Token permissions

### ISSUE THREAD

**Issue by spenserblack** [irevenko/octotui#1]
>Press `Generate new token` and select `repo, admin:org, user`

Does octotui really need *full* permissions for repositories, organizations, and user data? That seems like more permissions than necessary. What are the minimum token permissions necessary to use octotui?

**Comment by irevenko** [comment]
only ```user``` should be okay, updated README

**Comment by spenserblack** [comment]
Thanks for the quick response! Why is it that it needs full user permissions, and not just read:user?

**Comment by irevenko** [comment]
```read:user```, ```user:email``` are necessary
