### ISSUE TITLE
[BUG] `Something went wrong while executing your query`

### ISSUE THREAD

**Issue by spenserblack** [irevenko/octotui#2]
For some reason, when I try to look up my own username, I receive the error message `Something went wrong while executing your query`. I *can* look up other users, though. I did some digging, and it appears to be happening in `SetupProfileStats`.

**Comment by spenserblack** [comment]
This issue might need to be transferred to irevenko/github. The error seems to be happening in a call to `BuildUserStats`.

**Comment by spenserblack** [comment]
The error seems to be occurring in `github.com/irevenko/octostats/graphql.AllContributions`, so perhaps this issue should be transferred.

**Comment by spenserblack** [comment]
After looking into this some more, the error seems to be occurring from GitHub's graphql API itself. Using octostat, If I try to query myself, I get an error, *unless* I use a date range that returns no contributions (like setting `fromYear > toYear`). According to some GitHub Community threads, this seems to happen if too many resources are requested and the query times out, but I don't think this is what's happening, since I don't have a ridiculously high number of contributions.

I don't think this can be solved in here or on octostat, so maybe this issue should be closed.

***

Out of curiosity, could you (or someone else) check if I can be queried? I want to make sure the issue isn't coming from my API token or something.

**Comment by irevenko** [comment]
![image](https://user-images.githubusercontent.com/44785096/112863170-3d81c480-90bf-11eb-8973-342ff75f9a2f.png)

**Comment by spenserblack** [comment]
Thanks for checking! I wonder why I can't query myself, then :thinking:

I'll check on a different computer later -- it might have something to do with my personal setup.

**Comment by spenserblack** [comment]
Nevermind, I figured it out. It was my token, after all. IDK why, but `read:user` and `user:email` was sufficient to query *other* users, but not myself. :shrug: 

I set the permissions to `repo:status`, `read:org`, `read:user`, and `user:email`, and this seems to have given me enough access to query myself, other users, and organizations.

**Comment by irevenko** [comment]
yes star [octostats](https://github.com/irevenko/octostats) too
